### ISSUE TITLE
Display auto export doesn't work

### ISSUE THREAD

**Issue by pmdpaula** [Opticos/GWSL-Source#12]
I having problems with _Display Auto Export_
I'm getting these erros.

![image](https://user-images.githubusercontent.com/19227876/99533423-a4aaa200-2984-11eb-9075-f2c7fe067b63.png)

It is showing 5 times because I clicked 5 times in menu option. I thought that by clicking again it will uncheck the option and undo all changes.

So, how can a undo all changes by myself? Which files I have to watch?

**Comment by pmdpaula** [comment]
I found entries in .bashrc and .profile and delete all lines.

**Comment by Pololot64** [comment]
Yes only those two are changed. I have fixed this issue in the latest code but as with the other bug fixes, I cannot release immediately due to school.

**Comment by Dahrkael** [comment]
I just installed GWSL, this issue is still happening. Had to delete the ipconfig.exe autoexport lines and just hardcode the IP to get it working.

**Comment by Pololot64** [comment]
Do you have 1.3.7?

**Comment by Dahrkael** [comment]
the about says GWSL version 1.3.6 (store). isnt the store up to date after 2 months?

**Comment by Pololot64** [comment]
It will be tomorrow :D It was last week too but it broke Friday. It will be back tomorrow.

**Comment by Pololot64** [comment]
Apparently they have not certified it yet... Still waiting. . .

**Comment by Pololot64** [comment]
It is all out and everything should be working so I will close the issue
