### ISSUE TITLE
Shortcut creator appears to throw error in log

### ISSUE THREAD

**Issue by mtnygard** [Opticos/GWSL-Source#52]
# Steps to Reproduce

1. Left-click GWSL icon in tray
2. Menu pops up
3. Click "Shortcut creator"

# Expected behavior

The shortcut creator dialog box [shown in the manual](https://opticos.github.io/gwsl/tutorials/manual.html#using-the-gwsl-shortcut-creator) should appear.

# Actual behavior

No dialog appears. `dashboard.log` has the following lines appended:

```
2021-03-23 14:54:46,938 - GWSL 1.3.7 - ERROR - Exception occurred - Error in Mainloop
Traceback (most recent call last):
  File "manager.py", line 3244, in <module>
  File "manager.py", line 2901, in draw
  File "manager.py", line 2851, in short
  File "manager.py", line 2176, in shortcut
  File "manager.py", line 1897, in get_light
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

# Environment

Windows 10.1803.02.0006

Running Ubuntu 20.04 under WSL2.

**Comment by Pololot64** [comment]
Fixed in the code. Thanks for the feedback :)

**Comment by mtnygard** [comment]
I'm trying to run from a local build. I can't be sure I'm doing it right... not a Windows developer or a Python developer! 

As of 250a9703792 I still see the same behavior, error in the log file.

This is after running:

```
pipenv sync
pipenv shell
python build.py
cd dist\GWSL
GWSL.exe
```

Have I missed a step?

**Comment by Pololot64** [comment]
Strange. I did some new pushing just now. Can you test again? Technically this error should not be happening...

**Comment by mtnygard** [comment]
Good news! As of 2a094d0 the shortcut creator dialog appears as expected... though I have no idea how the last couple of commits would have changed that!

**Comment by Pololot64** [comment]
Hooray! I remember writing the fix about a month ago so I probably simply forgot to push the change. Sorry

**Comment by mi-hol** [comment]
Seems solved, hence should issue be closed to avoid confusions?

**Comment by Pololot64** [comment]
Good idea :)
