### ISSUE TITLE
Can't Open Apps from Linux Apps

### ISSUE THREAD

**Issue by mangkoran** [Opticos/GWSL-Source#59]
I am using ArchWSL in WSL2. Default shell is `fish`. Before using gwsl, I tried VcXsrv. I have this in my `config.fish` : `set -x DISPLAY (ip route | awk '/^default/{print $3; exit}'):0.0` and I can launch Linux GUI apps properly (e.g. `emacs`). When trying gwsl, I can't launch `emacs` from "Linux Apps" or "Shourcut Creator". But if I manually use "Linux Shell", and then execute `emacs`, Emacs opened. Here is my logfile: [dashboard.log](https://github.com/Opticos/GWSL-Source/files/6369008/dashboard.log)

**Comment by mangkoran** [comment]
Already tried [this](https://opticos.github.io/gwsl/tutorials/manual.html#using-gwsl-with-other-shells), but it still the same (need to manually open apps from Linux terminal). I guess even without this script, it should be fine?

**Comment by Pololot64** [comment]
I am assuming you have GWSL 1.3.7? This should be fixed in GWSL 1.3.8 but just in case it is not, what language/region is your pc and wsl set to?

**Comment by Pololot64** [comment]
Also, do you have the store version or github installer version of GWSL?

**Comment by mangkoran** [comment]
I reported this issue in 1.3.7, then tried the 1.3.8. Both still have the issue. I use GitHub version for both too.

**Comment by Pololot64** [comment]
And what language again? Sorry. It is an encoding issue

**Comment by mangkoran** [comment]
I guess this is what you asking?
![image](https://user-images.githubusercontent.com/57625126/115964066-31b9de80-a555-11eb-90cb-b40296d9101c.png)

**Comment by Pololot64** [comment]
Thanks. Thinking...

**Comment by Pololot64** [comment]
Here is a test build that should solve the issue. I did not have time to wrap it in an installer but you can extract it as is and run gwsl.exe. Just testing the app-launcher would be good. 
https://drive.google.com/file/d/1xUPUxnMCmGcAISlQo4tHpSihiLRspHwD/view?usp=sharing

Drive is the fastest way of sharing I can think of. I will remove the link after you get it

**Comment by mangkoran** [comment]
Downloaded. Going to test it now.

**Comment by mangkoran** [comment]
Still no luck. I cannot see any logfiles created.

**Comment by Pololot64** [comment]
Logfiles will still be in appdata/roaming/gwsl

**Comment by mangkoran** [comment]
Aside from cannot launch `emacs` from Shortcut Creator, the Linux Apps also displaying loading screen continuously. This is from 1.3.8 and still persist in your recently given build.
![image](https://user-images.githubusercontent.com/57625126/115965662-c116c000-a55c-11eb-9748-237ae835f056.png)

**Comment by mangkoran** [comment]
The only modified logfile is [service.log](https://github.com/Opticos/GWSL-Source/files/6370131/service.log).

**Comment by Pololot64** [comment]
What version and build of windows 10 do you have?

**Comment by Pololot64** [comment]
Service.log is unrelated... Wait did you edit your settings.json manually or add a profile?

**Comment by mangkoran** [comment]
Edition	Windows 10 Home
Version	20H2
Installed on	‎3/‎23/‎2021
OS build	19042.928
Experience	Windows Feature Experience Pack 120.2212.551.0

And no I didn't edit anything.

**Comment by Pololot64** [comment]
And you have wsl upgraded to at least support wsl2? The machines themselves do not need to be converted to 2

**Comment by mangkoran** [comment]
Yes my Arch is on WSL2.

Turns out the [dashboard.log](https://github.com/Opticos/GWSL-Source/files/6370135/dashboard.log) is modified earlier.

**Comment by Pololot64** [comment]
That is helpful but these do not mention anything about the new build 5 I sent you... Can you close any previously opened gwsl and run from the new folder again?

**Comment by mangkoran** [comment]
Still no luck. The dashboard.log is not updated either.

**Comment by Pololot64** [comment]
Hmm... can you possibly delete the appdata/roaming/GWSL folder completely and then restart the machine?

Technically the error should be fixed so I have no idea what is going on

**Comment by mangkoran** [comment]
Deleted and restarted, but still cannot open Apps.

**Comment by Pololot64** [comment]
Any new logs now?

**Comment by mangkoran** [comment]
Only [service.log](https://github.com/Opticos/GWSL-Source/files/6370171/service.log).

**Comment by Pololot64** [comment]
I know you did not change it but can you post your settings.json file?

**Comment by mangkoran** [comment]
Renamed it to .txt because GitHub doesn't support JSON [settings.json.txt](https://github.com/Opticos/GWSL-Source/files/6370177/settings.json.txt).

**Comment by Pololot64** [comment]
Oh! I think I know what is going on. Did you allow GWSL through the firewall when it asked?

**Comment by Pololot64** [comment]
And the app launcher still finds nothing and spins? Did it in 1.3.7? Sorry I think this is a combination of issues some of which are not bugs

**Comment by mangkoran** [comment]
Yes I allowed all of them. I tried to remove and re-add the entries (pointing to `GWSL_instance.exe` and `GWSL_vcxsrv.exe`

> And the app launcher still finds nothing and spins? Did it in 1.3.7? Sorry I think this is a combination of issues some of which are not bugs

No. In 1.3.7 it was fine. It showed the list of the apps, but cannot launch them.

**Comment by Pololot64** [comment]
Hope we are not wasting each other's time with confusion.. This is very bizarre. Especially since dashboard.log is never updated. Can you access the path `\\wsl$` in explorer?

**Comment by mangkoran** [comment]
Yes I can ![image](https://user-images.githubusercontent.com/57625126/115967353-d42d8e00-a564-11eb-9175-c3739fe37c32.png)

**Comment by Pololot64** [comment]
Rebuilt again... https://drive.google.com/file/d/1gwgvNryQEZD7HBWwQIdEXdb6b3XWooBy/view?usp=sharing

This one will print debug info to a live window. If it crashes copy the text from the debug window and it will close automatically in 10 seconds

**Comment by mangkoran** [comment]
This is the error log.
![image](https://user-images.githubusercontent.com/57625126/115967909-c9c0c380-a567-11eb-8653-856d9a5821d9.png)

I tinkered a bit around the error log, and found the issue. I also managed to fix the issue, which is something to do with my `fish` 's `conf.d`. Will update you tomorrow. It's 2 a.m. here.

**Comment by Pololot64** [comment]
Sleep well!

**Comment by mangkoran** [comment]
Just woke up. I immediately test both Shortcut Creator and Linux Apps, resuming yesterday solution. Both running fine now! I will elaborate my findings.

**Comment by mangkoran** [comment]
My current setup:
- ArchWSL, WSL2, running in Windows Terminal
- Fish shell, with some additions:
  - `ohmyfish`, `nvm`, `pure` (from `ohmyfish`), `base16-fish`
- GWSL 1.3.8 build 7

Referring to the error produced earlier, I suspect it has something to do with color settings. In my `.config/fish/conf.d` folder (which will be initialized every time I open a new terminal window), there is `base16.fish`. It calls `base16-*` function, which then set some shell variables for colors. The error message earlier indicate that some of the command in the `base16-fish` function called is not executed properly, and throwing the error when I tried to open the Linux Apps menu. It's the same when I tried to call a program from Shortcut Creator, but the error from Linux Apps menu has more information about the issue.

![image](https://user-images.githubusercontent.com/57625126/115979587-5e9fdd00-a5b9-11eb-9ca2-781b92cacff7.png)

After I disabled (commented all the lines) `base16.fish`, it works normally. I am able to launch program from both Shortcut Creator and Linux Apps. I don't know what is really happening here, but it's clearly the `base16-fish` that causing the error. If you need more information or wants me to do something, let me know.

**Comment by mangkoran** [comment]
Further investigation:

Testing this solution to previous build you have shared (public beta `1.3.8 build 4 and private beta 1.3.8 build 5 you shared). In build 4 the Linux Apps is showing the list of apps, so I guess it's working. But I cannot launch the app from it. In build 5, the issue is gone. So I think the problem you mentioned before (encoding) is the main issue for me.


> Here is a test build that should solve the issue. I did not have time to wrap it in an installer but you can extract it as is and run gwsl.exe. Just testing the app-launcher would be good.
> 
> Drive is the fastest way of sharing I can think of. I will remove the link after you get it

**Comment by Pololot64** [comment]
By any chance can you share your fish configuration and theme? Then I can try to harden the system from more bugs related to this. But everything is working normal now without too many changes to your system?

**Comment by mangkoran** [comment]
I will share it tomorrow.

> But everything is working normal now without too many changes to your system?

Yes. I think my method to change the terminal color was not typically used (because Windows Terminal theming is pain in the ass). I only use it for this WSL installation. I don't use this "change terminal color" method in my Linux because usually any terminal emulator provide a way to customize it's color.

**Comment by mangkoran** [comment]
Sorry for the late reply. [Here](https://github.com/mangkoran/dotfiles/tree/b5582e0637da18396116a1e48ec90659e834b870) is the repo for the `fish` config.

**Comment by Pololot64** [comment]
No problem (: Thanks!
